### ISSUE TITLE
Published package is not main branch

### ISSUE THREAD

**Issue by MarkusBiggus** [Katamave/sonnen_api_v2#3]
Hello,

I found your package whilst looking for Home Assistant Sonnen battery component that uses the V2 API.
It seemed to be just what I need and I noticed a comment about it not working quite right, I forked it and got everything working from the main branch.

I've just found the dev branch is being published to PyPi and is quite different to main and version numbers are quite different.
This is unexpected, only the main branch should be published when it's stable enough to release, so you only get a new version when dev branch is merged into main at release points.
I expected you're testing the package and publishing it to PyPi for that purpose, but that means any one using your package will get dev code, which they won't be expecting. (like me using main branch and its not the published package version)

You can set the default branch in your repo to 'dev' and use pip to install the dev package from github without publishing it to PyPi.
 see how to use a github package default branch:  https://pip.pypa.io/en/stable/cli/pip_install/#vcs-support

pip install "git+https://github.com/Katamave/sonnen_api_v2.git"

I'd like to help with development, if you're OK with that. 
My goal is to get weltmeyer Sonnenbatterie HA custom component working with your V2 API. 
My plan is to make a wrapper that takes the place of  weltmeyer "sonnenbatterie" API package and passes the calls to your API package, so the Sonnenbatterie component works without any modification. It will do this by using the same package name "sonnenbatterie" and be installed instead of weltmeyer package.
My ultimate goal with all this is to get HomeAssistant to send an alert when SonnenBatterie status changes to "offgrid" and make a component to show backup buffer usage when that happens.

Are you a Home Assistant user too? Does this sound like something you might like to use?

Look forward to your thoughts on all this.

Regards, Mark

**Comment by Katamave** [comment]
Hi, yes im HA user too. I have messed up with dev branch most of the time as im just a hobby dev :).

I have done some changes about 2 weeks ago but forgot to merge them... :). I can do it later tomorrow.
I have got some problems with data from remaining_capacity_wh api call and dont know why. Problem is still present.
Data im recieving is too high. 
I have a 22000wh system and with full charge api reports around 44000wh (maybe its a problem with configuration of my installlation).
I have asked sonnen but they told me that there is no support for a api.

Feel free to contribute if you like :).

**Comment by MarkusBiggus** [comment]
Hey, thanks for getting back to me.
Originally thought this package might have been abandoned when last changes were 2 years ago when I forked it.
You can see my changelog in the pull request I cancelled when I found new work on dev branch was in PyPi.
If you have a stable version on dev branch, merge that into main and publish main to PyPi.
I'll add your new changes to my work and try the pull request against to get backup buffer functions into the package.

Enable discussions on your repo and we can talk about stuff in discussions instead of this issue. 
I also get wrong values for remaining_capacity_wh, it's not double but close to double. I think maybe there is a way to calculate it from other numbers.

(I'm a dev btw, did a few refactors to make maintenance easier in the future)
